# DISCUSSION ON ROTATION: (TWP 2026-02-05)
# See Brown1983 page 105, C=cos(K*L), S=sin(K*L)
# [[ C**2  , iK*S*C  ,   S*C  , iK*S**2 ],
#  [-K*S*C ,  C**2   ,-K*S**2 ,   S*C   ],
#  [ -S*C  ,-iK*S**2 ,   C**2 , iK*S*C  ],
#  [ K*S**2,  -S*C   , -K*S*C ,  C**2   ]]
# which reduces to an identity matrix for L=0, C=1, S=0
# yet the "thin lens" approximation is:
#   1   0   0   0
# -1/f  1   0   0
#   0   0   1   0
#   0   0 -1/f  1
# consider the small angle approximation, S=linear K*L, C=1
# focusing goes by K*S*C ~=~ K^2*L, and rotation goes by S*C ~=~ K*L
# increasing K and decreasing L is thus able to maintain rotation while increasing focusing?
# and there appears to be no way to make the the above "converge" to the thin lens solution
# So what do we do when we'd like to, for example, fit for the length of a lens based on measured rotation of the image?
# if we update the length of a lens, we need to update the length of the drift section behind it
# using thin lenses only won't capture rotation
# we can also exclude the thickness of the lens during propagation (and therefore, eliminate the need to include it in the subsequent drift)
# passing "length=0" to Lens or Quadrapole will give rotation-free focusing (but inconsistent vs if a thickness were supplied, annoying)
# passing "ignoreLensThickness=True" to MicroscopeSection will exclude lense thicknesses from the stack to avoid needing to update the drifts

import numpy as xp
flag_gpu = False
import traceback
from pandas import DataFrame
from warnings import warn

from IPython.display import display # # TWP 2025/08/27 - adding import, required if not running inside IPython (e.g. outside of jupyter)

# CONVENTION: TWP 2025/09/08 - adding a columnByName function. if we use this universally, we can easily add or remove elements to the matrix
# [x,xθ,y,yθ,I,ϕ,E]
def columnByName(name): # function 
	return ["x","xt","y","yt","z","I","E"].index(name)

# TWP 2025/09/08 - this also means we should have *one* fixer function instead of each element having a conform_ray_dims function?
def fix_ray_dims(rays,columnNames):
	new=xp.zeros((len(rays),7))
	for i,name in enumerate(columnNames):
		new[:,columnByName(name)]=rays[:,i]
	return new

# TWP 2025/09/08 - we can also have a fixer function for the matrices
def fix_mat_dims(m,columnNames):
	new=xp.eye(7)
	for i,n1 in enumerate(columnNames):
		for j,n2 in enumerate(columnNames):
			new[columnByName(n1),columnByName(n2)]=m[i,j]
	return new

# Source element can be put in a MicroscopeSection and then propagating "through" the section will mean the starting rays r0 are generated by the Source (instead of requiring the user pass in starting rays)
class Source:
	def __init__(self, name:str=None,
			size:tuple=(2e-3,2e-3), # size in x and y (square grid)
			np_xy:tuple=(3,3),		# number of grid points in x and y
			angle:tuple=(1,1),		# angles in x,y (ranges of xt yt)
			na_xy:tuple=(3,3),
			position:float=None) -> object:
		
		self.name = name
		self.size = size
		self.np_xy = np_xy
		self.angle = angle
		self.na_xy = na_xy
		self.position = position
		self.length = 0
		self.kind = "Source"
		self.strength = 0
		self.calibration = None

	# Source term, initialize rays at sweep of angles and positions
	def rays(self):
		xs=xp.linspace(-self.size[0],self.size[0],self.np_xy[0])
		ys=xp.linspace(-self.size[1],self.size[1],self.np_xy[1])
		xts=xp.zeros(1) ; yts=xp.zeros(1)
		if self.angle[0]>0 and self.na_xy[0]:
			xts=xp.linspace(-self.angle[0],self.angle[0],self.na_xy[0])
		if self.angle[1]>0 and self.na_xy[1]:
			yts=xp.linspace(-self.angle[1],self.angle[1],self.na_xy[1])
		shape=(len(xs),len(ys),len(xts),len(yts))
		array=xp.zeros((len(xs)*len(ys)*len(xts)*len(yts),4))
		array[:,0]=(xs[:,None,None,None]*xp.ones(shape)).flat
		array[:,1]=(ys[None,:,None,None]*xp.ones(shape)).flat
		array[:,2]=(xts[None,None,:,None]*xp.ones(shape)).flat
		array[:,3]=(yts[None,None,None,:]*xp.ones(shape)).flat
		array=fix_ray_dims(array,["x","y","xt","yt"])
		array[:,columnByName("I")]=xp.ones(shape).flat
		return array

	# dummy propagation in case someone tries to propagate through since this is technically an element
	def propagate_ray(self, r0:xp.ndarray, **kwargs) -> xp.ndarray:
		return r0

class Element:
	def __init__(self, name:str='',
				 kind:str=None, poles:int=None,
				 position:float=None, length:float=0., radius:float=0,
				 strength:float=0, calibration:float=None,
				 ndim:int=2, chroma_dim:bool=False,
				 label:bool=False, print_fancy:bool=True
				 ) -> object:
		"""General microscope element class.

		Parameters
		----------
		name : str, optional
			Name given to the lens, by default ''
		kind : str, optional
			Type of element, by default None
		poles : None, int, optional
			Number of poles in the element.
			Drift = 0
			Dipole = 2
			Quadropole = 4
		position : float, optional
			The position of the element along the z-axis, by default 0
		length : int, optional
			Length of the element, by default 0
		strength : float, optional
			Defined as the field strength (related to inverse focal length,
			see equations in brown1983), by default 0
		calibration : float, optional
			Currnet calibration of the lens in units of ???/A, by default None
		ndim : int, optional
			The spatial dimensionality of the ray system perpendicular to propogation.
			The first-order lens matrix will have axes with size 2*ndim, which acounts for the derivatives.
			A 1D element without chromatic contributions will have `ndim=1`.
			A 2D element without chromatic contributions will have `ndim=2`.
		chroma_dim: bool, optional
			Is there a chromatic dimension, by default False
		label : bool, optional
			If the element should be labeled when plotted, by default False
		print_fancy : bool, optional
			If a fancy table should be used when printed, by default True

		"""
		self.name = name
		self.kind = kind
		self.poles = poles
		self.position = position
		self.length = length
		self.radius = radius
		self.strength = strength
		self.calibration = calibration
		self.ndim = ndim
		self.label = label
		self.print_fancy = print_fancy

	def kset(self,arg,val):
		self.__dict__.update({arg:val})
	def kget(self,arg):
		return self.__dict__[arg]

	def __repr__(self) -> str:
		rep = {'name':self.name,
			   'kind':self.kind,
			   'length':self.length,
			   'strength':self.strength,
			   'calibration':self.calibration,
			   }
		if  self.print_fancy:
			display(DataFrame({key:[value] for key, value in rep.items()}))
			return ''
		else:
			return '\t'.join([f"{key}: {value}, " for key, value in rep.items()])
	def __copy__(self):
		return type(self)(self.name, self.strength,self.calibration, self.label)

	def transfer_matrix(self,
						 s:float,
						 #type='Hills' TODO: Add `type` in paramaters to describe the type of transfer matrix. Hill's, Twiss, etc.
						 ) -> xp.ndarray:
		r"""Transfer matrix for ray propogation.
		
		The homogenous equaiton of motion approximation leads to a linear solution of $u"+k(s)u=0$ given as $u(s)=C(s)u_0+S(s)u_0', where s is the distance traveled (~z for small u').
		For K>0 $C=cos(\sqrt{Ks})$ and $S=\frac{1}{\sqrt{K}} sin(\sqrt{Ks})$ and for K<0 $C=cosh(\sqrt{|K|s})$ and $S=\frac{1}{\sqrt{|K|}} sinh(\sqrt{|K|s})$.
		The transfer matrix representation is then,
		$$ 
		T = \begin{matrix}
			C & S\\
			C' & S'
			\end{matrix}
		$$

		To Do
		-----
		TODO: Add `type` in paramaters to describe the type of transfer matrix. Hill's, Twiss, etc.
			Might need to move the bulk of the current function to a hidden function (e.g. __transfer_matrix_hills(...)) then call the hidden transfer matrix options.
		TODO: make the z initialization in propagate_ray or leave in here?
		"""
		poles = self.poles
		if poles is None:   raise ValueError('The number of poles is not set.')
		elif poles%2 != 0:  raise ValueError(f'Only even number poles are allowed. The current element has {poles:d} poles.')
		elif poles > 4:	 raise ValueError('Only multipoles with N<=4 are implemented (i.e. Quadropoles and lower).  The current element has {poles:d} poles.')
		else:			   pass
		
		#sK = xp.sqrt(xp.abs(self.strength))

		#Calculate transfer matrix.
		m = xp.eye(self.ndim*2)
		return m

	"""
	def conform_ray_dim(self, r0:xp.ndarray):
		""Recast the input arrays so they conform to 2*ndim+2.

		Parameters
		----------
		r0 : xp.ndarray
			List of rays with possible initial conditions (x, θx, y, θy, E).
			For 1D the (y, θy) coordinates are excluded.

		Returns
		-------
		ndarray
			Recast array.

		Raises
		------
		ValueError
			If the array can not be recase due to an incorrect length of rays.

		To do
		-----
		#TODO: Have this as an external function or in a "Ray" class
		""
		print(r0.shape,self.ndim,r0.shape[-1],self.ndim*2+1,r0.shape[-1]==self.ndim*2+1)
		if r0.shape[-1] == self.ndim*2+2:
			return r0
		elif r0.shape[-1] == self.ndim*2+1:
			#return xp.insert(r0, [1], xp.zeros(r0.shape[0]))
			return xp.insert(r0,-1,0,axis=1) # TWP 2025/08/27 - looks like we're trying to add a missing column, but what are the columns supposed to be? based on Lens, clearly 0,1,2,3 are x,angle,y,angle,but what are the last two?
		elif r0.shape[-1] == self.ndim*2:
			return xp.pad(r0, ((0,0), (0,2)), constant_values=0)
		else:
			raise ValueError(f'The last shape of the rays has size {r0.shape[-1]}, which can not be understood as ndim*2+(z, E), ndim*2+(E), or ndim*2')
	"""

	def propagate_ray(self, r0:xp.ndarray,
					  z:float=None, z0:float=0) -> xp.ndarray:
		"""propagate an array through an element.

		Parameters
		----------
		r0 : xp.ndarray
			List of rays with possible initial conditions (x, θx, y, θy, E).
		z : None | int | float | xp.ndarray, optional
			Positions in the element to propagate to by default None
		z0 : None | float, optional
			Initial position of the element, by default 0

		Returns
		-------
		xp.ndarray
			List of propagated rays with initial condition (x, θx, y, θy, z, E)
		"""
		m = self.transfer_matrix(s=self.length)
		rf = xp.einsum('mn,in->im', m, r0) # matrix multiplication for a "list of vectors"
		rf[:,columnByName("z")] = r0[:,columnByName("z")]+self.length

		return rf

class Aperture(Element):
	def __init__(self, name:str='', 
			 position:float=None, radius:float=0.,
			 calibration:float=None,length:float=0,
			 label:bool=False, print_fancy:bool=True) -> object:
		super().__init__(name=name,
						 kind='Aperture', poles=0,
						 position=position, radius=radius,
						 calibration=calibration, length=length,
						 label=label, print_fancy=print_fancy)
	def transfer_matrix(self,
						 s:float
						 #type='Hills' TODO: Add `type` in paramaters to describe the type of transfer matrix. Hill's, Twiss, etc.
						 ) -> xp.ndarray:
		r"""Transfer matrix for ray propogation.
		"""
		#print("WARNING: APERTURE",self.name,"TRANSFER MATRIX CALLED")
		#m = xp.eye(6)#[...,None]*xp.ones_like(s)
		m = xp.eye(4) # drift tube updates x from xθ and y from yθ
		return fix_mat_dims(m,["x","xt","y","yt"])

	# TWO WAYS TO IMPLEMENT AN APERTURE:
	# 1) set the intensity of any rays "outside" the aperture to zero. this is fine for plotting but i'm not sure we can use this for fitting. For example, suppose I zero-out intensities, then my least-squares deviation function looks at the largest x,y value for non-zeroed rays to infer the beam diameter post-aperture. as i creep a ray towards the aperture edge, i'll get step-edges in my deviation function when a ray pops into view or pops out of view. we can capture beam current by looking at how many rays are zeroed out
	# 2) aperture could rescale all rays based on the outer ray at this point. we're thus pretending the originating rays were less divergent or something which is actually what we see IRL; you can't tell the divergence of the beam from the gun because the VOA masks out a bunch of it. This will only work for one aperture in the system though (otherwise second aperture undoes the scaling of the first one? or should we only allow the aperture to scale-down, so if the first aperture scales down, second scales down further (second is smaller), or first scale down, second leaves it alone (second is larger, we'd be able to see our first aperture in the CCD for example). and how do we handle apertures of different shapes?? and how do we calculate beam current? do we reduce intensity based on the scaling factor we needed to apply?
	#def propagate_ray(self, r0:xp.ndarray,
	#				  z:float=None, z0:float=0) -> xp.ndarray:
	#	rf=xp.zeros(r0.shape)+r0
	#	radii=xp.sqrt( r0[:,columnByName("x")]**2 + r0[:,columnByName("y")]**2 )
	#	rf[radii>self.radius,columnByName("I")]=0
	#	return rf
	def propagate_ray(self, r0:xp.ndarray,
					  z:float=None, z0:float=0) -> xp.ndarray:
		xmax = xp.amax(r0[:,columnByName("x")])
		ymax = xp.amax(r0[:,columnByName("y")])
		scale_x = 1 if xmax<self.radius else self.radius/xmax
		scale_y = 1 if ymax<self.radius else self.radius/ymax
		#print("Aperture",self.name,"radius",self.radius,"scale x,y",scale_x,scale_y,"(",xmax,ymax,")")
		rf=xp.zeros(r0.shape)+r0
		rf[:,columnByName("x")]*=scale_x
		rf[:,columnByName("xt")]*=scale_x
		rf[:,columnByName("y")]*=scale_y
		rf[:,columnByName("yt")]*=scale_y
		rf[:,columnByName("I")]*=scale_x*scale_y
		#try:
		#dafgsdg
		#except Exception as e:
		#	print(traceback.print_exc())
		return rf


class Drift(Element):
	def __init__(self, name:str='', 
				 position:float=None, length:float=0.,
				 calibration:float=None,
				 label:bool=False, print_fancy:bool=True) -> object:
		"""Quadripole.

		Parameters
		----------
		name : str, optional
			Name given to the lens, by default ''
		position : float, optional
			The position of the element along the z-axis, by default 0
		length : int, optional
			Length of the element, by default 0
		calibration : float, optional
			Currnet calibration of the lens in units of ???/A, by default None
		label : bool, optional
			If the element should be labeled when plotted, by default False
		print_fancy : bool, optional
			If a fancy table should be used when printed, by default True
		"""
		
		super().__init__(name=name,
						 kind='Drift', poles=0,
						 position=position, length=length,
						 calibration=calibration,
						 label=label, print_fancy=print_fancy)
	def transfer_matrix(self,
						 s:float
						 #type='Hills' TODO: Add `type` in paramaters to describe the type of transfer matrix. Hill's, Twiss, etc.
						 ) -> xp.ndarray:
		r"""Transfer matrix for ray propogation.
		"""
		
		#m = xp.eye(6)#[...,None]*xp.ones_like(s)
		m = xp.eye(4) # drift tube updates x from xθ and y from yθ

		if self.calibration is not None:
			s *= self.calibration

		if self.length != 0:
			m[0,1] = s
			m[2,3] = s
		elif self.length == 0:
			pass

		return fix_mat_dims(m,["x","xt","y","yt"])

class Quadrapole(Element):
	def __init__(self, name:str='', 
				 position:float=None, length:float=0.,
				 strength:float=0, calibration:float=None,
				 label:bool=False, print_fancy:bool=True) -> object:
		"""Quadripole.

		Parameters
		----------
		name : str, optional
			Name given to the lens, by default ''
		position : float, optional
			The position of the element along the z-axis, by default 0
		length : int, optional
			Length of the element, by default 0
		strength : float, optional
			Defined as the field strength (related to inverse focal length,
			see equations in brown1983), by default 0
		calibration : float, optional
			Currnet calibration of the lens in units of ???/A, by default None
		label : bool, optional
			If the element should be labeled when plotted, by default False
		print_fancy : bool, optional
			If a fancy table should be used when printed, by default True
		"""
		
		if length == 0: kind = 'Thin quad'
		else:		   kind = 'Quad'
		super().__init__(name=name,
						 kind=kind, poles=4,
						 position=position, length=length, 
						 strength=strength, calibration=calibration,
						 label=label, print_fancy=print_fancy)
	def transfer_matrix(self,
						 s:float
						 #type='Hills' TODO: Add `type` in paramaters to describe the type of transfer matrix. Hill's, Twiss, etc.
						 ) -> xp.ndarray:
		r"""Transfer matrix for ray propogation.
		
		The homogenous equaiton of motion approximation leads to a linear solution of $u"+k(s)u=0$ given as $u(s)=C(s)u_0+S(s)u_0', where s is the distance traveled (~z for small u').
		For K>0 $C=cos(\sqrt{Ks})$ and $S=\frac{1}{\sqrt{K}} sin(\sqrt{Ks})$ and for K<0 $C=cosh(\sqrt{|K|s})$ and $S=\frac{1}{\sqrt{|K|}} sinh(\sqrt{|K|s})$.

		To Do
		-----
		"""
		
		#m = xp.eye(6)#[...,None]*xp.ones_like(s) # TWP 2025/08/27 - adding ones_like expression so m is 6x6x1, otherwise eigsum in propagate will fail
		#m = xp.eye(4) # quadrupole updates xθ from x and yθ from y

		if self.strength==0:
			return fix_mat_dims(xp.eye(4),["x","xt","y","yt"])

		K=self.strength
		if self.calibration is not None:
			# linear scaling from mA (lens current) to lens strength?
			if isinstance(self.calibration,(int,float)):
				c = self.calibration
				K *= c
			else:
				c,p = self.calibration
				K = K**p * c

		if self.length==0:
			print("using special")
			X=xp.asarray([[ 1 , 0 ],
					     [ -(K**2) , 1 ]])
			Y=xp.asarray([[ 1 , 0 ],
						 [  (K**2) , 1 ]])
			if K>0: # testing with REMOVED_PRIVATE_INSTRUMENT_TREE/PRIVATE_INSTRUMENT_v2/DQCM.py, sign flip is needed for len=0.08,cal=1 vs len=0,cal=sqrt(0.08)
				X,Y=Y,X
			#print("X",fix_mat_dims(X,["x","xt"]))
			#print("Y",fix_mat_dims(X,["y","yt"]))
		else:
			kL=K*self.length ; L=self.length
			C=xp.cos(kL) ; S=xp.sin(kL)
			#print("K,L,C,S",K,L,C,S)
			X=xp.asarray([[  C  , 1/K*S ],  # Brown1983 page 46, note the similarity to
						[-K*S ,   C   ]]) # https://en.wikipedia.org/wiki/Ray_transfer_matrix_analysis#Example:_Thin_lens if L=0
			Y=xp.asarray([[  C  , 1/K*S ],  # calculate x,xt and y,yt 2x2s separately, then matmul
						[ K*S ,   C   ]])
			# Small angle approximation: C=1, S=K*L
			#X=xp.asarray([[  1 , L ],
			#			[-K*K*L, 1   ]])
			#Y=xp.asarray([[  1 , L ],
			#			[ K*K*L,  1  ]])

		m=xp.matmul( fix_mat_dims(X,["x","xt"]) , fix_mat_dims(Y,["y","yt"]) )
		#print("QUAD",m,self.strength,K,self.calibration,self.length)
		return m
		
		#if self.length != 0:
		#	sK = xp.sqrt(xp.abs(self.strength))
		#	#get trig functions for transfer matrix
		#	C = xp.cos(sK*s)
		#	S = 1/sK * xp.sin(sK*s)
		#	dC = -sK * xp.sin(sK*s)
		#	dS = C
		#	trig = xp.array([[C ,  S],
		#					 [dC, dS]])
		#	Ch = xp.cosh(sK*s)
		#	Sh = 1/sK * xp.sinh(sK*s)
		#	dCh =  sK * xp.sinh(sK*s)
		#	dSh = Ch
		#	trigh = xp.array([[Ch ,  Sh],
		#					  [dCh, dSh]])
		#	if self.strength>0: #focusing, trig funcitons
		#		m[:2, :2] = trig
		#		m[2:4,2:4] = trigh
		#	elif self.strength<0: #defocusing, hyperbolic trig functions
		#		m[:2, :2] = trigh
		#		m[2:4,2:4] = trig
		#	else: #drift
		#		m = Drift.transfer_matrix(s)
		#elif self.length == 0:
		#	f = self.strength
		#	if self.strength>0:
		#		m[1,0] = -1/f
		#		m[3,2] = 1/f
		#	elif self.strength>0:
		#		m[1,0] = 1/f
		#		m[3,2] = -1/f
		#	else: #off
		#		pass
		#
		#return fix_mat_dims(m,["x","xt","y","yt"])

class Lens(Element):
	def __init__(self, name:str='', 
				 position:float=None, length:float=0.,
				 strength:float=0, calibration:float=None,
				 label:bool=False, print_fancy:bool=True, rotation:bool=False) -> object:
		"""Quadripole.

		Parameters
		----------
		name : str, optional
			Name given to the lens, by default ''
		position : float, optional
			The position of the element along the z-axis, by default 0
		length : int, optional
			Length of the element, by default 0
		strength : float, optional
			Defined as the field strength (related to inverse focal length,
			see equations in brown1983), by default 0
		calibration : float, optional
			Currnet calibration of the lens in units of ???/A, by default None
		label : bool, optional
			If the element should be labeled when plotted, by default False
		print_fancy : bool, optional
			If a fancy table should be used when printed, by default True
		"""
		
		if length == 0: kind = 'Thin lens'
		else:		   kind = 'QLens'
		super().__init__(name=name,
						 kind=kind, poles=None,
						 position=position, length=length, 
						 strength=strength, calibration=calibration,
						 label=label, print_fancy=print_fancy)
		self.rotation = rotation
	def transfer_matrix(self,
						 s:float
						 #type='Hills' TODO: Add `type` in paramaters to describe the type of transfer matrix. Hill's, Twiss, etc.
						 ) -> xp.ndarray:
		r"""Transfer matrix for ray propogation.
		"""

		if self.strength==0:
			return fix_mat_dims(xp.eye(4),["x","xt","y","yt"])

		K=self.strength
		if self.calibration is not None:
			# linear scaling from mA (lens current) to lens strength?
			if isinstance(self.calibration,(int,float)):
				c = self.calibration
				K *= c
			else:
				c,p = self.calibration
				K = K**p * c

		if self.length==0:
			X=xp.asarray([[    1   , 0 ],
					     [ -(K**2) , 1 ]])
			Y=xp.asarray([[    1   , 0 ],
						 [ -(K**2) , 1 ]])
			return xp.matmul( fix_mat_dims(X,["x","xt"]) , fix_mat_dims(Y,["y","yt"]) )
		else:
			kL=K*self.length ; iK=1/K
			C=xp.cos(kL) ; S=xp.sin(kL)
			XY=xp.asarray([[ C**2  , iK*S*C  ,   S*C  , iK*S**2 ],	# Brown1983 page 105
						   [-K*S*C ,  C**2   ,-K*S**2 ,   S*C   ],	# similar to standard
						   [ -S*C  ,-iK*S**2 ,   C**2 , iK*S*C  ],	# [  1   0 ] but with
						   [ K*S**2,  -S*C   , -K*S*C ,  C**2   ]] )# [ -1/f 1 ] rotation
			if not self.rotation:
				zeroer=xp.asarray([[1,1,0,0],[1,1,0,0],[0,0,1,1],[0,0,1,1]])
				XY*=zeroer
			return fix_mat_dims(XY,["x","xt","y","yt"])

class Prism(Element):
	def __init__(self, name:str='', 
				 position:float=None, length:float=0.,
				 radius:float=None, angle:float=45., w:float=1., g:float=1., k1:float=0.,
				strength:float=0, calibration:float=None,
				 label:bool=False, print_fancy:bool=True) -> object:
		"""Prism.

		Parameters
		----------
		name : str, optional
			Name given to the lens, by default ''
		position : float, optional
			The position of the element along the z-axis, by default 0
		length : int, optional
			Length of the element, by default 0
		strength : float, optional
			Defined as the field strength (related to inverse focal length,
			see equations in brown1983), by default 0
			Note this in not the focusing strength (K) and is simply f.
			A thin lens is defind as KL=-1/fas L goes to zero.
		calibration : float, optional
			Currnet calibration of the lens in units of ???/A, by default None
		label : bool, optional
			If the element should be labeled when plotted, by default False
		print_fancy : bool, optional
			If a fancy table should be used when printed, by default True

		To do
		-----
		#TODO: Include dispersion (R16). See Egerton eq 2.14
		#TODO: Include other spectrometer aberrations. See Egerton eq 2.13
		"""

		self.angle = angle
		self.angle_rad = xp.deg2rad(angle)
		if radius is not None and length is not None:
			raise ValueError('Only specify the length or radius as providing both with radius is not unique.')
		elif radius is not None:
			length = angle_rad * radius
		elif length is not None:
			radius = length/angle_rad 
		else:
			raise ValueError('Either radius or length need to be specified.')

		super().__init__(name=name,
						 kind='Prism', poles=2,
						 position=position, length=length,
						 strength=strength, calibration=calibration,
						 label=label, print_fancy=print_fancy)
		self.radius = radius
		self.w = w
		self.g = g
		self.K1 = k1

	def focus_matrix(self,
					 #type='Hills' TODO: Add `type` in paramaters to describe the type of transfer matrix. Hill's, Twiss, etc.
					 ) -> xp.ndarray:
		r"""Transfer matrix for the entrance/exit surfaces of the spectrometer used for ray propogation.
		"""
		m = xp.eye(6)

		if self.strength!=0:
			m[1,0] = xp.tan(self.strength) / self.radius
			if k1 == 0:
				m[1,0] = - xp.tan(self.strength) / self.radius
			else: #include fringe fields
				psi = (self.g/self.R) * self.k1 * (1+xp.sin(self.strength)**2)/xp.cos(self.strength)
				m[2:4,2:4] = - xp.tan(self.strength - psi) / self.radius
		else: #drif
			pass

		return fix_mat_dims(m,["x","xt","y","yt","z","E"])
	
	def bending_matrix(self,
					   s:float,
					   #type='Hills' TODO: Add `type` in paramaters to describe the type of transfer matrix. Hill's, Twiss, etc.
					   ) -> xp.ndarray:
		r"""Transfer matrix for the bending of the spectrometer used for ray propogation.
		"""
		m = xp.eye(6)
		u = s/self.radius

		if self.strength!=0:
			m[0,0] = xp.cos(u)
			m[1,1] = xp.cos(u)
			m[0,1] = self.radius * xp.sin(u)
			m[1,0] = - xp.sin(u)/self.radius
		else:
			m = Drift.transfer_matrix(s)

		return fix_mat_dims(m,["x","xt","y","yt","z","E"])
		
	def transfer_matrix(self,
						 s:float,
						 #type='Hills' TODO: Add `type` in paramaters to describe the type of transfer matrix. Hill's, Twiss, etc.
						 ) -> xp.ndarray:
		r"""Transfer matrix for ray propogation.
		"""
		
		m_focus1 = self.focus_matrix()
		m_bend   = self.bending_matrix(s)
		m_focus2 = self.focus_matrix()

		m = m_focus2 @ m_bend @ m_focus1

		return fix_mat_dims(m,["x","xt","y","yt","z","E"])

