import numpy as xp
flag_gpu = False
import traceback
from warnings import warn
from abc import abstractmethod

from .seashells import SEASerializable

# CONVENTION: Rays are defined by positions laterally (x,y), angles (xt,yt, "t" for theta θ or tilt), position down column (z), intensities (I, e.g. when an aperture masks the beam and the overall intensity is reduced), and energy E
# rays at a given position are 2D: a list up septuplets (grab the 'x' column to grab each ray's x position for example).
# rays throughout the microscope are 3D: a list of the above.
# currently, the columns are ordered: [x,xθ,y,yθ,I,ϕ,E]
# but with the columnByName function used universally, additional columns can be added without every Element needing to be updated, and columns can be reordered arbitrarily.

# given a keyword, return the column associated. r0[:,columnByName('x')] should return every ray's x position
def columnByName(name):
	return ["x","xt","y","yt","z","I","E"].index(name)
# given a transfer_matrix defined by a subset of columns (e.g. a 2x2 lens for focusing in x only) "inflate" out to 7x7 based on convention set by columnByName. [ x₂ θ₂ ] = [2x2] @ [ x₁ θ₁ ] (https://en.wikipedia.org/wiki/Ray_transfer_matrix_analysis) would become [ x₂ xθ₂ y₂ yθ₂ ....] = [7x7] @ [ x₁ xθ₁ y₁ yθ₁....]
def fix_mat_dims(m,columnNames):
	new=xp.eye(7)
	for i,n1 in enumerate(columnNames):
		for j,n2 in enumerate(columnNames):
			new[columnByName(n1),columnByName(n2)]=m[i,j]
	return new
# similar to fix_mat_dims, but for rays
def fix_ray_dims(rays,columnNames):
	new=xp.zeros((len(rays),7))
	for i,name in enumerate(columnNames):
		new[:,columnByName(name)]=rays[:,i]
	return new

class Element(SEASerializable):
	def __init__(self, name:str='', kind:str=None ) -> object:
		"""General microscope element class. Only the basic/required attributes (name and kind) are populated, as additional attributed can be defined at the inheriting class level. e.g. a Lens has a "strength", but a Drift section does not.
		Inheriting classes are required to define a transfer_matrix (enforced via abstractmethod), and *may* define a custom propagate_ray function if the standard "[ x₂ xθ₂ y₂ yθ₂ ....] = [7x7] @ [ x₁ xθ₁ y₁ yθ₁....]" is not applicable

		Parameters
		----------
		name : str, optional
			Name given to the lens, by default ''
		kind : str, optional
			Type of element, by default None
		"""
		self.name = name
		self.kind = kind

	# print function: look for specific attributes on inheriting class object, and display as columns
	def __repr__(self,header=True) -> str:
		whitelist = [ "name", "kind", "position", "length", "strength", "calibration" ]
		rep = { k:getattr(self,k) for k in self.__dict__ if k in whitelist }
		#rep = {'name':self.name,
		#	   'kind':self.kind,
		#	   }
		h = [] ; s = []
		for k,v in rep.items():
			h.append(k+" "*(8-len(k)))
			if v is None:
				v="[None]"
			if isinstance(v,float):
				v = xp.round(v,7)
			v=str(v) ; v=v+" "*(8-len(v)) ; v=v[:8]
			s.append(v)
		if header:
			return " ".join(h)+"\n"+" ".join(s)
		return " ".join(s)

	def __copy__(self):
		return type(self)(self.name, self.kind)

	@abstractmethod # abstractmethod means a class which inherits Element will be required to define this function
	def transfer_matrix(self) -> xp.ndarray:
		r"""Transfer matrix for ray propogation: https://en.wikipedia.org/wiki/Ray_transfer_matrix_analysis
		This will typically be defined in terms of ray position x,y, and ray angles xt,yt.
		inheriting class only needs to define with the relevant parameters, then inflate using fix_mat_dims
		"""
		pass

	def propagate_ray(self, r0:xp.ndarray,
					  z:float=None, z0:float=0) -> xp.ndarray:
		"""propagate an array through an element.

		Parameters
		----------
		r0 : xp.ndarray
			List of rays with possible initial conditions (x, θx, y, θy, E).
		z : None | int | float | xp.ndarray, optional
			Positions in the element to propagate to by default None
		z0 : None | float, optional
			Initial position of the element, by default 0

		Returns
		-------
		xp.ndarray
			List of propagated rays with initial condition (x, θx, y, θy, z, E)
		"""
		m = self.transfer_matrix()
		rf = xp.einsum('mn,in->im', m, r0) # matrix multiplication for a "list of vectors"
		rf[:,columnByName("z")] = r0[:,columnByName("z")]+self.length
		return rf

class Source(Element):
	"""Source element class. Source element can be put in a MicroscopeSection and then propagating "through" the section will mean the starting rays r0 are generated by the Source (instead of requiring the user pass in starting rays)

		Parameters
		----------
		name : str, optional
			Name of the Source, by default ''
		size : tuple, optional
			size in x and y: rays will be emitted from a square grid of points
		np_xy : tuple, optional
			number of grid points in x and y
		angle : tuple, optional
			maximum angle in x and y: rays will be emitted at multiple angles from each grid point
		na_xy : tuple, optional
			number of angles for emitted rays in x and y
		position : float, optional
			The position of the element along the z-axis, by default 0
		"""

	def __init__(self, name:str=None,
			size:tuple=(2e-3,2e-3), # size in x and y (square grid)
			np_xy:tuple=(3,3),		# number of grid points in x and y
			angle:tuple=(1,1),		# angles in x,y (ranges of xt yt)
			na_xy:tuple=(3,3),
			position:float=None) -> object:

		self.name = name
		self.size = size
		self.np_xy = np_xy
		self.angle = angle
		self.na_xy = na_xy
		self.position = position
		self.length = 0
		self.kind = "Source"
		self.strength = 0
		self.calibration = None

	# Source term, initialize rays at sweep of angles and positions
	def rays(self):
		xs=xp.linspace(-self.size[0],self.size[0],self.np_xy[0])
		ys=xp.linspace(-self.size[1],self.size[1],self.np_xy[1])
		xts=xp.zeros(1) ; yts=xp.zeros(1)
		if abs(self.angle[0])>0 and self.na_xy[0]:
			xts=xp.linspace(-self.angle[0],self.angle[0],self.na_xy[0])
		if abs(self.angle[1])>0 and self.na_xy[1]:
			yts=xp.linspace(-self.angle[1],self.angle[1],self.na_xy[1])
		shape=(len(xs),len(ys),len(xts),len(yts))
		array=xp.zeros((len(xs)*len(ys)*len(xts)*len(yts),4))
		array[:,0]=(xs[:,None,None,None]*xp.ones(shape)).flat
		array[:,1]=(ys[None,:,None,None]*xp.ones(shape)).flat
		array[:,2]=(xts[None,None,:,None]*xp.ones(shape)).flat
		array[:,3]=(yts[None,None,None,:]*xp.ones(shape)).flat
		array=fix_ray_dims(array,["x","y","xt","yt"])
		array[:,columnByName("I")]=xp.ones(shape).flat
		return array

	# dummy propagation in case someone tries to propagate through since this is technically an element
	def propagate_ray(self, r0:xp.ndarray, **kwargs) -> xp.ndarray:
		return r0

class Aperture(Element):
	"""Aperture element class. An aperture serves to crop the beam, and the total beam intensity is reduced dependent on the area of the beam and the area of aperture.

		Parameters
		----------
		name : str, optional
			Name of the Aperture, by default ''
		radius : float, optional
			radius of the round aperture
		calibration : float, optional
			linear scaling factor applied to the radius. e.g. nominally 2mm aperture but fitting tells us it is actually 1.95
		position : float, optional
			The position of the element along the z-axis, by default 0
		"""

	def __init__(self, name:str='', radius:float=0., calibration:float=None, position:float=None) -> object:
		super().__init__(name=name, kind='Aperture')
		self.position = position
		self.radius = radius
		self.calibration = calibration

	#def transfer_matrix(self) -> xp.ndarray:
	#	r"""Transfer matrix for ray propogation.
	#	"""
	#	#print("WARNING: APERTURE",self.name,"TRANSFER MATRIX CALLED")
	#	#m = xp.eye(6)#[...,None]*xp.ones_like(s)
	#	m = xp.eye(4) # drift tube updates x from xθ and y from yθ
	#	return fix_mat_dims(m,["x","xt","y","yt"])

	# TWO WAYS TO IMPLEMENT AN APERTURE:
	# 1) set the intensity of any rays "outside" the aperture to zero. this is fine for plotting and we can capture beam current by looking at how many rays are zeroed out. *BUT*, this will be problematic during fitting, as rays which "pop" into and out of view will yield an intensity vs [whatever] function with step edges.
	# def propagate_ray(self, r0:xp.ndarray,
	#				  z:float=None, z0:float=0) -> xp.ndarray:
	#	rf=xp.zeros(r0.shape)+r0
	#	radii=xp.sqrt( r0[:,columnByName("x")]**2 + r0[:,columnByName("y")]**2 )
	#	rf[radii>self.radius,columnByName("I")]=0
	#	return rf
	# 2) aperture can rescale all rays based on the outer ray's position, or the area covered by the rays. we can thus calculate reductions in beam current based on the aperture's reduction in intensity (area cropped out). we're effectively pretending the originating rays were less divergent or something, which is actually sort of what we see IRL; you can't tell the divergence of the beam from the gun because the VOA masks out a bunch of it. This will only work for one aperture in the system though (otherwise second aperture undoes the scaling of the first one? or should we only allow the aperture to scale-down, so if the first aperture scales down, second scales down further (second is smaller), or first scale down, second leaves it alone (second is larger, we'd be able to see our first aperture in the CCD for example). and how do we handle apertures of different shapes??
	def propagate_ray(self, r0:xp.ndarray,
					  z:float=None, z0:float=0) -> xp.ndarray:
		xmax = xp.amax(r0[:,columnByName("x")])
		ymax = xp.amax(r0[:,columnByName("y")])
		scale_x = 1 if xmax<self.radius else self.radius/xmax
		scale_y = 1 if ymax<self.radius else self.radius/ymax
		#print("Aperture",self.name,"radius",self.radius,"scale x,y",scale_x,scale_y,"(",xmax,ymax,")")
		rf=xp.zeros(r0.shape)+r0
		rf[:,columnByName("x")]*=scale_x
		rf[:,columnByName("xt")]*=scale_x
		rf[:,columnByName("y")]*=scale_y
		rf[:,columnByName("yt")]*=scale_y
		rf[:,columnByName("I")]*=scale_x*scale_y
		return rf

class Drift(Element):
	"""Drift element class for free-space propagation.

		Parameters
		----------
		name : str, optional
			Name of Drift segment, useful for creating named planes which do not affect beam propagation (e.g., a "sample plane")
		length : float, optional
			length for free-space propagation
		calibration : float, optional
			linear scaling applied to length. e.g. nominally we believe the next lens is at 10 mm, but maybe fitting says 9.9
		position : float, optional
			The position of the element along the z-axis, by default None

		References
		----------
		https://en.wikipedia.org/wiki/Ray_transfer_matrix_analysis#Free_space_example
		"""

	def __init__(self, name:str='', length:float=0., calibration:float=None, position:float=None) -> object:

		super().__init__(name=name,kind='Drift')
		self.position = position
		self.length = length
		self.calibration = calibration

	def transfer_matrix(self) -> xp.ndarray:

		m = xp.eye(4) # drift tube updates x from xθ and y from yθ

		s = self.length

		if self.calibration is not None:
			s *= self.calibration

		if s != 0:
			m[0,1] = s
			m[2,3] = s
		elif self.length == 0:
			pass

		return fix_mat_dims(m,["x","xt","y","yt"])

class Quadrapole(Element):
	def __init__(self, name:str='', 
				 position:float=None, length:float=0.,
				 strength:float=0, calibration:float=None) -> object:

		"""Quadripole.

		Parameters
		----------
		name : str, optional
			Name given to the lens, by default ''
		position : float, optional
			The position of the element along the z-axis, by default 0
		length : int, optional
			Length of the element, by default 0
		strength : float, optional
			Defined as the field strength (related to inverse focal length,
			see equations in brown1983), by default 0
		calibration : float, optional
			Currnet calibration of the lens in units of ???/A, by default None
		label : bool, optional
			If the element should be labeled when plotted, by default False
		print_fancy : bool, optional
			If a fancy table should be used when printed, by default True
		"""
		
		if length == 0: kind = 'Thin quad'
		else:		   kind = 'Quad'

		super().__init__(name=name,kind=kind)
		self.position = position
		self.length = length
		self.strength = strength
		self.calibration = calibration

	def transfer_matrix(self) -> xp.ndarray:
		r"""Transfer matrix for ray propogation.
		
		The homogenous equaiton of motion approximation leads to a linear solution of $u"+k(s)u=0$ given as $u(s)=C(s)u_0+S(s)u_0', where s is the distance traveled (~z for small u').
		For K>0 $C=cos(\sqrt{Ks})$ and $S=\frac{1}{\sqrt{K}} sin(\sqrt{Ks})$ and for K<0 $C=cosh(\sqrt{|K|s})$ and $S=\frac{1}{\sqrt{|K|}} sinh(\sqrt{|K|s})$.

		To Do
		-----
		"""
		
		#m = xp.eye(6)#[...,None]*xp.ones_like(s) # TWP 2025/08/27 - adding ones_like expression so m is 6x6x1, otherwise eigsum in propagate will fail
		#m = xp.eye(4) # quadrupole updates xθ from x and yθ from y

		K=self.strength
		if self.calibration is not None:
			# linear scaling from mA (lens current) to lens strength?
			if isinstance(self.calibration,(int,float)):
				c = self.calibration
				K *= c
			else:
				c,p = self.calibration
				K = K**p * c

		if K==0:
			return fix_mat_dims(xp.eye(4),["x","xt","y","yt"])

		if self.length==0:
			print("using special")
			X=xp.asarray([[ 1 , 0 ],
					     [ -(K**2) , 1 ]])
			Y=xp.asarray([[ 1 , 0 ],
						 [  (K**2) , 1 ]])
			if K>0: # testing with REMOVED_PRIVATE_INSTRUMENT_TREE/PRIVATE_INSTRUMENT_v2/DQCM.py, sign flip is needed for len=0.08,cal=1 vs len=0,cal=sqrt(0.08)
				X,Y=Y,X
			#print("X",fix_mat_dims(X,["x","xt"]))
			#print("Y",fix_mat_dims(X,["y","yt"]))
		else:
			kL=abs(K*self.length) ; L=self.length
			C=xp.cos(kL) ; S=xp.sin(kL)
			#print("K,L,C,S",K,L,C,S)
			X=xp.asarray([[  C  , 1/K*S ],  # Brown1983 page 46, note the similarity to
						[-K*S ,   C   ]]) # https://en.wikipedia.org/wiki/Ray_transfer_matrix_analysis#Example:_Thin_lens if L=0
			Y=xp.asarray([[  C  , 1/K*S ],  # calculate x,xt and y,yt 2x2s separately, then matmul
						[ K*S ,   C   ]])
			# Small angle approximation: C=1, S=K*L
			#X=xp.asarray([[  1 , L ],
			#			[-K*K*L, 1   ]])
			#Y=xp.asarray([[  1 , L ],
			#			[ K*K*L,  1  ]])

		m=xp.matmul( fix_mat_dims(X,["x","xt"]) , fix_mat_dims(Y,["y","yt"]) )
		#print("QUAD",m,self.strength,K,self.calibration,self.length)
		return m
		

class Lens(Element):
	"""Lens element class for round lenses / symmetric focusing. https://en.wikipedia.org/wiki/Ray_transfer_matrix_analysis#Thin_lens_example or Brown1983 page 105

		Parameters
		----------
		name : str, optional
			Name of the lens, by default ''
		length : float, optional
			thickness of the lens, which affects the rotation of the beam
		strength : float, optional
			lens strength, proportional to lens current I, or magnetic field strength B. strength^2 is propogational to 1/f
		calibration : list or float, optional
			if a float is provided, a linear scaling will be applied to strength
			if a list is provided, terms are used in a series: strength =A+B*nominal+C*nominal^(1/2)+D*nominal^(1/3)+...
		position : float, optional
			The position of the element along the z-axis, by default None
		rotation : bool, optional
			if set to False, lens rotation for finite-thickness lenses is overridden and turned off.
		"""
	def __init__(self, name:str='', length:float=0.,
				 strength:float=0, calibration:float=None,
				 position:float=None, rotation:bool=False) -> object:
		
		if length == 0: kind = 'Thin lens'
		else:		   kind = 'QLens'

		super().__init__(name=name,kind=kind)
		self.position = position
		self.length = length
		self.strength = strength
		self.calibration = calibration
		self.rotation = rotation

	def transfer_matrix(self) -> xp.ndarray:
		r"""Transfer matrix for ray propogation.
		"""

		# HANDLE CALIBRATION SCALING
		K=self.strength
		if self.calibration is not None:
			# linear scaling from mA (lens current) to lens strength?
			if isinstance(self.calibration,(int,float)):
				c = self.calibration
				K *= c
			else:
				# A + B*x + C*x^2 + ...(as many terms as you want)
				#Kvals = [ v*K**i for i,v in enumerate(self.calibration) ]
				#K = sum( Kvals ) ; print(self.calibration,self.strength,Kvals)
				# A + B*x^(1/1) + C*x^(1/2) + D*x^(1/3) + ....
				Kvals = [self.calibration[0]] + [ v*K**(1/(i+1)) for i,v in enumerate(self.calibration[1:]) ]
				K = sum( Kvals ) ; print(self.calibration,self.strength,Kvals)
				#K = sum( [self.calibration[0]] + [ v*K**(1/(i+1)) for i,v in enumerate(self.calibration[1:]) ] )
				#c,p = self.calibration
				# A + B*x**C + D*x**E + ...
				#K = self.calibration[0]
				#for a,b in zip(self.calibration[1::2],self.calibration[2::2]):
				#	print(a,b)
				#	K += a*self.strength**b
				#K = K**p * c

		# FINITE LENGTH LENS, ZERO STRENGTH = DRIFT (try inserting a zero-strength lens and seeing if the result changes)
		if K==0:
			m = xp.eye(4)
			m[0,1]=self.length
			m[2,3]=self.length
			return fix_mat_dims(m,["x","xt","y","yt"])

		# THIN LENS, NO ROTATION (thick lens math will have sine term going to zero)
		if self.length==0:
			X=xp.asarray([[    1   , 0 ],
					     [ -(K**2) , 1 ]])
			Y=xp.asarray([[    1   , 0 ],
						 [ -(K**2) , 1 ]])
			return xp.matmul( fix_mat_dims(X,["x","xt"]) , fix_mat_dims(Y,["y","yt"]) )

		# THICK LENS, FINITE K (zero K will have iK going to infinite)
		kL=K*self.length ; iK=1/K
		C=xp.cos(kL) ; S=xp.sin(kL)
		XY=xp.asarray([[ C**2  , iK*S*C  ,   S*C  , iK*S**2 ],	# Brown1983 page 105
						[-K*S*C ,  C**2   ,-K*S**2 ,   S*C   ],	# similar to standard
						[ -S*C  ,-iK*S**2 ,   C**2 , iK*S*C  ],	# [  1   0 ] but with
						[ K*S**2,  -S*C   , -K*S*C ,  C**2   ]] )# [ -1/f 1 ] rotation
		if not self.rotation:
			zeroer=xp.asarray([[1,1,0,0],[1,1,0,0],[0,0,1,1],[0,0,1,1]])
			XY*=zeroer
		return fix_mat_dims(XY,["x","xt","y","yt"])

class Prism(Element):
	def __init__(self, name:str='', 
				 position:float=None, length:float=0.,
				 radius:float=None, angle:float=45., w:float=1., g:float=1., k1:float=0.,
				strength:float=0, calibration:float=None) -> object:
		"""Prism.

		Parameters
		----------
		name : str, optional
			Name given to the lens, by default ''
		position : float, optional
			The position of the element along the z-axis, by default 0
		length : int, optional
			Length of the element, by default 0
		strength : float, optional
			Defined as the field strength (related to inverse focal length,
			see equations in brown1983), by default 0
			Note this in not the focusing strength (K) and is simply f.
			A thin lens is defind as KL=-1/fas L goes to zero.
		calibration : float, optional
			Currnet calibration of the lens in units of ???/A, by default None
		label : bool, optional
			If the element should be labeled when plotted, by default False
		print_fancy : bool, optional
			If a fancy table should be used when printed, by default True

		To do
		-----
		#TODO: Include dispersion (R16). See Egerton eq 2.14
		#TODO: Include other spectrometer aberrations. See Egerton eq 2.13
		"""

		self.angle = angle
		self.angle_rad = xp.deg2rad(angle)
		if radius is not None and length is not None:
			raise ValueError('Only specify the length or radius as providing both with radius is not unique.')
		elif radius is not None:
			length = angle_rad * radius
		elif length is not None:
			radius = length/angle_rad 
		else:
			raise ValueError('Either radius or length need to be specified.')

		super().__init__(name=name,kind='Prism')
		self.position = position
		self.length = length
		self.strength = strength
		self.calibration = calibration
		self.radius = radius
		self.w = w
		self.g = g
		self.K1 = k1

	def focus_matrix(self,
					 #type='Hills' TODO: Add `type` in paramaters to describe the type of transfer matrix. Hill's, Twiss, etc.
					 ) -> xp.ndarray:
		r"""Transfer matrix for the entrance/exit surfaces of the spectrometer used for ray propogation.
		"""
		m = xp.eye(6)

		if self.strength!=0:
			m[1,0] = xp.tan(self.strength) / self.radius
			if k1 == 0:
				m[1,0] = - xp.tan(self.strength) / self.radius
			else: #include fringe fields
				psi = (self.g/self.R) * self.k1 * (1+xp.sin(self.strength)**2)/xp.cos(self.strength)
				m[2:4,2:4] = - xp.tan(self.strength - psi) / self.radius
		else: #drif
			pass

		return fix_mat_dims(m,["x","xt","y","yt","z","E"])
	
	def bending_matrix(self,
					   s:float,
					   #type='Hills' TODO: Add `type` in paramaters to describe the type of transfer matrix. Hill's, Twiss, etc.
					   ) -> xp.ndarray:
		r"""Transfer matrix for the bending of the spectrometer used for ray propogation.
		"""
		m = xp.eye(6)
		u = s/self.radius

		if self.strength!=0:
			m[0,0] = xp.cos(u)
			m[1,1] = xp.cos(u)
			m[0,1] = self.radius * xp.sin(u)
			m[1,0] = - xp.sin(u)/self.radius
		else:
			m = Drift.transfer_matrix(s)

		return fix_mat_dims(m,["x","xt","y","yt","z","E"])
		
	def transfer_matrix(self) -> xp.ndarray:
		r"""Transfer matrix for ray propogation.
		"""
		
		m_focus1 = self.focus_matrix()
		m_bend   = self.bending_matrix(self.strength)
		m_focus2 = self.focus_matrix()

		m = m_focus2 @ m_bend @ m_focus1

		return fix_mat_dims(m,["x","xt","y","yt","z","E"])
